version: '2.0'

services:
  database:
    image: "mongo:latest"
    ports:
      - 27017:27017
    volumes:
      - ./database:/data/db

  api:
    build: ./api
    ports:
      - 8080:8080
    depends_on:
      - database

  frontend:
    build: ./frontend
    # volumes:  # docker-compose will discard all changes made in build time when using volumes
    #   - ./frontend:/frontend
    ports:
      - 80:80
    depends_on:
      - api
