version: '2.0'

services:
  database:
    image: "mongo:latest"
    ports:
      - 27017:27017
    volumes:
      - ./database:/data/db

  backend:
    build: ./backend
    ports:
      - 8080:8080
    depends_on:
      - database

  frontend:
    build: ./frontend
    ports:
      - 80:80
    depends_on:
      - backend
