version: '2.0'

services:
  database:
    image: "mongo:latest"
    ports:
      - 27017:27017
    volumes:
      - ./database:/data/db

  api:
    build: ./api
    ports:
      - 8080:8080
    volumes:
      - ./api:/usr/src/app
    depends_on:
      - database

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/frontend
    ports:
      - 80:80
    depends_on:
      - api